# Site settings
title: 
header-img: img/home-bg.png
email: mackdaniels@protonmail.com
copyright_name: mackdaniels
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mackdaniels
learn_profile: mackdaniels
email_username: mackdaniels@protonmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
